spring:
  application:
    name: ms-account

server:
  port: 8971

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: ${HOSTNAME:localhost}
