spring:
  application:
    name: ms-customer

server:
  port: 8830

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: ${HOSTNAME:localhost}

#bootstrap.properties

#application.properties
#application.yml
